---
- name: Ensure firewalld is installed.
  yum: name=firewalld state=installed

- name: Ensure firewalld is started and enabled to start at boot.
  service: name=firewalld state=started enabled=yes
